# Generated by Django 3.2.8 on 2021-11-18 04:05

from django.db import migrations, models
import django.db.models.fields.related


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_social_network_soc_net_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='social_network',
            name='image',
        ),
        migrations.RemoveField(
            model_name='social_network',
            name='link',
        ),
        migrations.RemoveField(
            model_name='social_network',
            name='soc_net_name',
        ),
        migrations.RemoveField(
            model_name='social_network',
            name='url',
        ),
        migrations.CreateModel(
            name='Social_Network_Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('url', models.SlugField(unique=True)),
                ('link', models.CharField(max_length=500)),
                ('image', models.ImageField(upload_to='social_networks/')),
                ('soc_net_name', models.ForeignKey(on_delete=django.db.models.fields.related.ForeignKey, to='blog.social_network')),
            ],
        ),
    ]
