# Generated by Django 3.2.8 on 2021-11-18 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20211117_2005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='social_network_post',
            name='name',
        ),
        migrations.RemoveField(
            model_name='social_network_post',
            name='url',
        ),
    ]
