# Generated by Django 3.2.8 on 2021-11-18 05:12

from django.db import migrations, models
import django.db.models.fields.related


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20211117_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='social_network_post',
            name='soc_net_name',
            field=models.ForeignKey(on_delete=django.db.models.fields.related.ForeignKey, related_name='net', to='blog.social_network'),
        ),
    ]
