# Generated by Django 3.2.9 on 2021-11-13 10:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('travelix', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recreation_area',
            options={'ordering': ['-date_created']},
        ),
        migrations.AddField(
            model_name='recreation_area',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='recreation_area',
            name='date_updated',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
