# Generated by Django 3.2.9 on 2021-11-13 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelix', '0002_auto_20211113_1520'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Recreation_area',
            new_name='Rest_area',
        ),
    ]
