# Generated by Django 3.2.9 on 2021-11-13 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelix', '0004_auto_20211113_0721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rest_area',
            name='bottom_images',
            field=models.ImageField(blank=True, null=True, upload_to='<django.db.models.fields.CharField>/recreation_pics/bottoms'),
        ),
    ]
