# Generated by Django 3.2.9 on 2021-11-13 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelix', '0005_alter_rest_area_bottom_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rest_area',
            name='from_date',
            field=models.DateField(default=0, verbose_name='Enter valid starting date'),
        ),
        migrations.AlterField(
            model_name='rest_area',
            name='limit_date',
            field=models.DateField(default=0, verbose_name='Enter valid ending date'),
        ),
    ]
