# Generated by Django 3.2.9 on 2021-11-13 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelix', '0006_auto_20211113_0727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rest_area',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='rest_area',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
