# Generated by Django 3.2.9 on 2021-11-13 16:53

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelix', '0008_auto_20211113_0809'),
    ]

    operations = [
        migrations.AddField(
            model_name='rest_area',
            name='text',
            field=ckeditor.fields.RichTextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='review',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
