# Generated by Django 3.2.9 on 2021-11-14 06:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('travelix', '0009_auto_20211113_0853'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rest_area',
            options={'ordering': ['date_created']},
        ),
        migrations.AddField(
            model_name='rest_area',
            name='dislikes',
            field=models.ManyToManyField(related_name='post_dislikes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rest_area',
            name='likes',
            field=models.ManyToManyField(related_name='post_likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rest_area',
            name='rest_views',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
