# Generated by Django 3.2.9 on 2021-11-14 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelix', '0014_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='image',
            field=models.ImageField(default=0, upload_to='clients/'),
            preserve_default=False,
        ),
    ]
