# Generated by Django 3.2.9 on 2021-11-14 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travelix', '0015_client_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='travelix.category'),
        ),
    ]
