# Generated by Django 3.2.9 on 2021-11-14 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travelix', '0016_client_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category', to='travelix.category'),
        ),
    ]
