# Generated by Django 3.2.9 on 2021-11-14 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelix', '0018_alter_client_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='rest_area',
            name='city',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rest_area',
            name='state',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
