# Generated by Django 3.2.8 on 2021-11-15 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelix', '0019_auto_20211114_0529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rest_area',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=6),
        ),
    ]
