# Generated by Django 3.2.8 on 2021-11-15 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelix', '0020_alter_rest_area_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='category',
        ),
    ]
