# Generated by Django 3.2.8 on 2021-11-15 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelix', '0021_remove_client_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='client',
            new_name='author',
        ),
    ]
