# Generated by Django 3.2.8 on 2021-11-17 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travelix', '0023_auto_20211117_0343'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='rest',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='travelix.rest_area'),
            preserve_default=False,
        ),
    ]
