# Generated by Django 3.2.8 on 2021-11-17 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travelix', '0024_review_rest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='rest',
        ),
        migrations.AddField(
            model_name='rest_area',
            name='review',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='travelix.review'),
        ),
    ]
