# Generated by Django 3.2.8 on 2021-11-17 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travelix', '0026_rest_area_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rest_area',
            name='review',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='travelix.review'),
        ),
    ]
