# Generated by Django 3.2.8 on 2021-11-17 17:11

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelix', '0030_rename_url_rest_area_map_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rest_area',
            name='map_url',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
