# Generated by Django 3.2.8 on 2021-11-17 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelix', '0031_alter_rest_area_map_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rest_area',
            name='map_url',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
