# Generated by Django 3.2.8 on 2021-11-21 07:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('travelix', '0035_auto_20211118_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rest_area',
            name='dislikes',
            field=models.ManyToManyField(blank=True, related_name='rest_dislikes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='rest_area',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='rest_likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
